# Generated by Django 5.0.3 on 2024-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='movie_title',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
