# Generated by Django 5.0.3 on 2024-05-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0002_listentry_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listentry',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='listentry',
            name='poster_url',
        ),
    ]
