# Generated by Django 5.0.6 on 2024-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0003_remove_listentry_movie_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='poster_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
