# Generated by Django 5.0.6 on 2024-05-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0004_listentry_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listentry',
            name='movie_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
